Set default mouse cursor in code, not project.godot
When I first set the default cursor in commit
8e736dbd424425ac2ac79e6e1675ef877b86e9cd ("Add custom mouse pointer"), I
wrote:

> Doing this in project.godot only overrides the default cursor shape;
> other shapes (I-beam, hand, etc.) must be done in code. I believe we
> don't use any other shapes in the game so let's use project.godot.

Since commit 4dc1272e3972f4999e85bd2fa943e9f1f3f8b3b9 ("Mouse manager:
Set custom cursor for cross shape") that last sentence is no longer
true. It is more consistent to specify all the custom cursors in one
place, in the code.

In addition, setting the cursor in code rather than in project.godot
works around a Godot bug where specifying the cursor in project.godot
causes an error when the project is first imported into the editor,
because the image is accessed before the project has been scanned so the
UID is unknown:

    ERROR: Unrecognized UID: "uid://cee2juvnxco6c".
        at: get_id_path (core/io/resource_uid.cpp:199)
    ERROR: Condition "local_path.is_empty()" is true. Returning: Ref<ResourceLoader::LoadToken>()
        at: _load_start (core/io/resource_loader.cpp:568)

The downside of doing it this way is that the OS default cursor will be
seen until the mouse_managers autoload is initialized. I don't think
this is a significant issue.

Resolves https://github.com/endlessm/threadbare/issues/1838