Don't infer PhantomCamera-based variable types
On initial import, these lines caused the following errors (and
cascading script compilation errors):

> ERROR: res://scenes/globals/camera_utilities/camera_utilities.gd:8 -
> Parse Error: Cannot infer the type of "phantom_camera_hosts" variable because the value doesn't have a set type.

> ERROR: res://scenes/quests/lore_quests/quest_002/2_grappling_hook/components/grappling_hook_powerup.gd:22 -
> Parse Error: Cannot infer the type of "cameras" variable because the value doesn't have a set type.

> ERROR: res://scenes/quests/lore_quests/quest_002/3_void_grappling/components/void_grapping_round_2.gd:28 -
> Parse Error: Cannot infer the type of "cameras" variable because the value doesn't have a set type.

This is because during first import the custom types defined by the
addon are not known to the engine.

Specifying the variable types directly rather than using `:=` fixes
this.

Resolves https://github.com/endlessm/threadbare/issues/2288